repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argo-workflows
    chart: argo/argo-workflows
    version: 0.22.13
    namespace: argo-workflows
    createNamespace: true
    kubeContext: minikube
    values:
      - ./values.yaml